### ISSUE TITLE
Pagination implementation for real-life database

### ISSUE THREAD

**Issue by mattecapu** [graphql/graphql-relay-js#94] opened 2016-06-19 10:32 UTC
In all the examples I can find, paginated queries are made against a mockup database which is just a JS array, and thus it is simply passed through `connectionFromArray` to return the correct paginated result (like the Star Wars example mentioned in the README).
For a real-life database, query _all_ records and then pass them to `connectionFromPromisedArray` doesn't seem to be a very good solution, because you're fetching a huge number of records, a lot of which you don't even need.

So what solutions should do you use to avoid insane database fetching?

(I'm using a SQL database but I think a good solution to this problem applies to pretty much every not-a-js-array dbms)

**Comment by OlegIlyenko** [comment] 2016-06-19 13:04
Recently @chandu0101 created a nice and relatively big example of a relay application which uses MongoDB and [sangria](http://sangria-graphql.org/) (scala GraphQL implementation).

If you don't mind looking at some scala code, then I would suggest to check out this function:

https://github.com/chandu0101/sri-sangria-example/blob/master/server/src/main/scala/sri/sangria/mongoserver/services/BaseService.scala#L52-L99

It creates a relay `Connection` which is based on MongoDB query. It also properly handles relay-style pagination and the result set, which comes from the DB, always contains only relevant documents. This particular example uses mongo's `skip` and `limit` to archive this. But I can also imagine other strategies to do this - for instance using an `ID`-based cursors which would be even more efficient.

Even though this example uses [sangria-relay](https://github.com/sangria-graphql/sangria-relay), conceptually it is very similar to reference implementation.

**Comment by GuillaumeLeclerc** [comment] 2016-07-07 10:05
From all the solutions I found on the internet (including this one). It seems it does not work if data is inserted in the database during the lifetime of a cursor.

Am I wrong ?

Is there a generic solution ?

**Comment by GuillaumeLeclerc** [comment] 2016-07-08 07:17
I thought about a solution to solve the data insertion:

- If there is no before nor after cursor I execute the database query but I only select the Ids, not the content. generate a new queryId (uuidv4) and save the Id's I get to a redis hastable where the key is the queryId
- If there is a cursor I extract the queryId from the cursor and get the list of Id's from the database
- I use the query args to compute which Id's the client is interested in
- I make a database query including the corresponding Ids
- Return the result

I have a compliant implementation for Mongoose database I can share if anyone interested.

My only concern Is how long should I keep the queries in my redis server.

**Comment by sibelius** [comment] 2016-07-12 11:07
@mattecapu this package [relay-mongodb-connection](https://github.com/mikberg/relay-mongodb-connection) creates relay connection from mongodb cursors, it also uses `skip` and `limit`

**Comment by mattecapu** [comment] 2016-07-12 16:32
Thank you @sibelius and @OlegIlyenko, your links were a good starting place for understanding what was going on in the creation of a ConnectionType response.

My solution was to not use `createConnection*` utilities but to create a ConnectionType response by myself.

Essentially I encode information about the ordering field (i.e. the ID) in the cursor and then use that to query results with ID >= or <= than cursor. The `first` and `last` parameters are handled with some clever `LIMIT`ing and order reversing.

My actual use case was a little more complicated because I'm fetching from multiple tables. Thus after retrieving the minimum required records I'm doing an additional round of sorting and cutting.

I'd be happy to provide some code examples if someone needs them.

**Comment by sibelius** [comment] 2016-07-12 17:42
@mattecapu I think u should provide some code examples to help people understand better how to implement a cursor

**Comment by mattecapu** [comment] 2016-07-13 16:29
Well the point is, if you implement a ConnectionType for an endpoint you just need to

* accept `connectionArgs` parameters
* return a suitable response in the shape `{ edges: [{ cursor, node }], pageInfo: { hasNextPage, hasPreviousPage, startCursor, endCursor }`

Cursors can be any string you want. Normally Relay defaults to `arrayconnection:<id>` converted to base64 to make it opaque (you shouldn't actually relay on the implementation details of the cursors).

I used `<type_name>:<id>` converted to base64 as cursors.

Then a request to my endpoint look like this
```graphql
endpoint(after: "sdflkjsdlfkjslkdf", first: 10) {
   # stuff
}
```
Basically, any request described by [the specification](https://facebook.github.io/relay/graphql/connections.htm) is supported.

Thus when I get the request I process it in the following way:

1. Start from the greedy query: `SELECT * FROM table`
1. If the `after` argument is provided, add `id > parsed_cursor` to the `WHERE` clause
1. If the `before` argument is provided, add `id < parsed_cursor` to the `WHERE` clause
1. If the `first` argument is provided, add `ORDER BY id DESC LIMIT first+1` to the query
1. If the `last` argument is provided, add `ORDER BY id ASC LIMIT last+1` to the query
1. If the `last` argument is provided, I reverse the order of the results
1. If the `first` argument is provided then I set `hasPreviousPage: false` (see spec for a description of this behavior).
1. If no less than `first+1` results are returned, I set `hasNextPage: true`, otherwise I set it to `false`.
1. If the `last` argument is provided then I set `hasNextPage: false` (see spec for a description of this behavior).
1. If no less `last+1` results are returned, I set `hasPreviousPage: true`, otherwise I set it to `false`.

Using this "algorithm", only the needed data is fetched. While `after` and `before` can be both set, I make sure `first` and `last` args are treated as mutually exclusive to avoid making a mess. The spec itself discourage making requests with both the arguments set.

Notably, I return an object with the shape described above (and in the linked spec) and I don't use the `connectionFromArray` helper, which expects a *raw* collection to slice accordingly to the args.

**Comment by wincent** [comment] 2016-08-30 00:07
That's a really great write-up @mattecapu. I'm going to close this out now but that is exactly the kind of thing that would work well in the documentation (could be something in a code comment, in the `README`, or we could start an `examples` folder). Would be happy to look at a PR adding something like that.

**Closed by wincent** 2016-08-30 00:07 UTC

**Comment by GuillaumeLeclerc** [comment] 2016-08-30 02:55
@mattecapu It seems the algorithm does not work if there was an deletion in the database between two paginated queries and/or if we want to sort by anything else than Id's right ?

**Comment by oexza** [comment] 2016-09-23 23:20
@mattecapu what happens when the ids are not ordered? i.e they are UUIDs, `id > paresedValue` will be useless.

**Comment by mattecapu** [comment] 2016-09-24 13:41
Sorry @GuillaumeLeclerc I lost your question in a notification misunderstanding with GitHub.
I'm going to address your question together with @oexza new comment.

As laid out in the comment above, my algorithm as both the limitations you guys noticed, but we can easily generalize it to overcome both at once using creation timestamps as "order-providers", instead of abusing of the `id` field, which by the way isn't guaranteed to be sequential anyway (in my specific use case, it was).

To support dynamic data getting deleted or added inbetween queries, paginating with `creationTime` works like a charm, especially with Relay caching mechanism.

We can provide a further generalization by not fixing an order-provider field but let it be dynamic, effectively allowing a lot of different orders on the data, which can come in handy. This is pretty simple to implement too, but gets complicated once you have to support dynamic data too. I supect there's no silver bullet for this use case, but I might be wrong.

@wincent I'll see what I can do! Thanks for the appreciation.

**Comment by joonhocho** [comment] 2016-09-30 00:10
I came across this issue and I wanted to share a Node.js library that I created a while ago.
https://github.com/joonhocho/graphql-relay-connection
It helps you easily create a custom relay connections.
You can create connections for MongoDB, simple number arrays, etc by providing few functions.
I hope this can help.

**Comment by Naoto-Ida** [comment] 2016-11-02 15:28
@mattecapu Great post! Just wanted to say it helped out a lot. We had some tweaking to do since we accept arguments other than the Relay args spec.

**Comment by Naoto-Ida** [comment] 2016-11-08 08:50
Everything was working great with @mattecapu's solution,
but I ran into one rare situation as such and am in quite a pickle...
wondering if any of you have run into this issue.

We have one query for events that returns data in a specific order.
This specific order, which is passed as part of an SQL statement, includes things like how many times that event's page has been viewed, whether it has an promotional image, etc. Basically about 5 `*** DESC`s in `ORDER BY`.

We have an events query like this:
````js
{
  viewer {
    events(first: 1, inCountry: Japan) {
      edges {
        node {
          id
          name
        }
      }
    }
  }
}
````

`first` and `last` can be dealt with as addressed above; flip the multiple `ORDER BY DESC` to `ORDER BY ASC`.

But when you introduce `after` & `before`, it is very difficult to serve the correct data that corresponds to the given Node ID, as due to the nature of our query, it is not as simple as saying `event.id > 1` or `event.createAt > xxxx` when `after` & `before` are passed.

**Comment by mattecapu** [comment] 2016-11-08 18:26
@Naoto-Ida if I understood correctly and your order is deterministic, `createAt` attribute should do the trick.
How do you compute your `cursor`s?

**Comment by Naoto-Ida** [comment] 2016-11-09 09:14
@mattecapu 

Our ORDER statement in our SQL would include something like:
ORDER BY
1. closest to user location
2. amount of views
3. whether its free, etc.
Or something like that. It would differ drastically depending on the user and "when" you query it, so it does not work off the `createAt`. Sorry, maybe my example of using `createAt` was misleading.
What I was trying to get at was that your method works great in situations where ordering is based on a single factor.

We compute it by base64decoding it, and splitting it into `object:ID`. From there we get that one record and get the ones before/after that.

So in the end, due to there not being that many records and time constraints, we redis cached the all the event record. We fetch it when a query with the same arguments come in, then based off of the supplied cursor, would slice the total records and serve the ones before/after it.

**Comment by mattecapu** [comment] 2016-11-09 17:52
Now I see the problem.
When I was writing my algorithm, my implicit assumption was that between two different queries, the only change that could happen to the database was addition or removal of records.
While this may be a good-enough assumption for most cases, it fails if, like in your case, there's a third way to mutate the state of your database: updating a record.
That messes up with my algorithm because **I cannot tell wether a given record was changed from the last time I queried the db**.
Yet, **this is not a problem specific to my algorithm**. In general, **there's no way to do this without storing information about updates**.
Likewise, without storing a `createdAt` attribute there's no way to tell if a given record was there when I first run the query (apart from using other time-related information stored in the record, such as a sequential ID).
So the only way to support such constraint is to **change the architecture of your db**, adopting some kind of time-traveling structure.
Eventually, this is not as difficult as it sounds.
**For the general case**, you'll have to store every update you make to your db.
So your records will now look like this
```
object_id | updated_attribute | new_value | timestamp
```
Your data will be shattered into several of this *atomic* operations, which aggregated togheter will give you the most recent version of it. So for example if I want to retrieve attribute `name` of object `34` I'll ask my db
```sql
SELECT new_value FROM mytable WHERE object_id='34' ORDER BY timestamp DESC LIMIT 1
```
But now If I want to know which state my db was as a given time, I'll simply exclude all updates done after a specific timestamp_
```
SELECT new_value FROM mytable WHERE object_id='34' AND timestamp < GIVEN_TIMESTAMP
 ORDER BY timestamp DESC LIMIT 1
```
Voilà, I can now run queries against any version of my DB.
Obviously this is a simplification, you'll have a lot of issues to address (or better, _operations to translate_) to support this kind of architecture, but it's the only/best way to support such problem constraints.

Speaking for your specific case, @Naoto-Ida, I think you could get away with a far less disruptive change: create a table `views(post_id, timestamp)` and calculate `amountOfViews` at query-time by aggregating with the foreign key of your main table. That way you can filter by `timestamp` and retrieve the state (and thus the order) you had at that time.

**Comment by luckydrq** [comment] 2017-10-31 06:40
>4. If the first argument is provided, add ORDER BY id DESC LIMIT first+1 to the query

@mattecapu why `+1` to `limit` number? I think it is just as equal as first argument.

**Comment by Naoto-Ida** [comment] 2017-10-31 12:34
@luckydrq You add `+1` to get the boolean for `pageInfo.hasNextPage`

**Comment by mattecapu** [comment] 2017-11-05 13:33
@luckydrq yeah it basically peeks at the next page to see if there is one.

Re-reading my last post, it comes to me there's a less invasive way to support updates, just use an `updatedAt` attribute. Use it the same way you use the createdAt attribute, and update it on updates.

**Comment by pcattori** [comment] 2018-01-03 20:50
I implemented some helper functions so that SQL support would be easy (ordering, filtering supported).

in short:

```js
import {
    GraphQLObjectType,
} from 'graphql'
import {
    connectionArgs,
    connectionDefinitions,
} from 'graphql-relay'

import * as helpers from 'the-gist-linked-below' // not an actual npm lib yet :P

// helper
const connectionType = nodeType => connectionDefinitions({nodeType}).connectionType

const Query = new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
        // ... other queries here
        things: {
            type: connectionType(Thing),
            args: connectionArgs,
            resolve: (_, paginationArgs) => {
                return helpers.paginate(models.Thing, paginationArgs, {orderBy: [['name', 'ASC']]})
            }
        },
    })
})
```

https://gist.github.com/pcattori/2bb645d587e45c9fdbcabf5cef7a7106

**Comment by sibelius** [comment] 2018-01-03 21:08
We use this in production

https://github.com/entria/graphql-mongoose-loader

it solves pagination and dataloader for mongo, using mongoose.

we have the same concept for other datasources, as REST api, SQL (oracle and postgres), very easy to extend to any datasource.

**Comment by crisu83** [comment] 2018-04-26 07:02
@mattecapu Thanks for posting your solution here it was very helpful. 

I implemented the same logic in our project on top of our [GraphQL](https://github.com/digiaonline/graphql-php) and [Relay](https://github.com/digiaonline/graphql-relay-php) implementation in PHP.

**Comment by enumag** [comment] 2018-10-02 15:19
@mattecapu I read your [guide](https://github.com/graphql/graphql-relay-js/issues/94#issuecomment-232410564) how to handle GraphQL connections with SQL. It's pretty much what I came up with when I was analyzing it myself (+ some details like how to handle hasNextPage). 

The problem is that the SQL query gets really complicated really fast when I add a sorting argument to the GraphQL connection - especially if the sorting can be a combination of fields.

Do you have any tips how to handle that efficiently?

**Comment by mattecapu** [comment] 2018-10-02 20:31
Hi @enumag, what do you exactly mean by 'SQl complexity'? The length in chars? Execution time? Other metrics?
I will assume you mean 'the query it writes is an ugly monster made up of a lot of chunks'. Unfortunately, my algorithm (feels weird to call it in such a way...) is very straightforward, and I really can't think of any ways to make it shorter or to improve its 'efficiency'. It really just translates between GraphQL and SQL, so I don't see room of improvement without pruning feature from your endpoint.
That said, using SQL builders means that you never deal with the raw, horrific string, and using an ORM means an even nicer interface (I use Sequelize). I would hint at this as a good practice, because it abstracts away much of the trouble.

**Comment by enumag** [comment] 2018-10-03 14:20
> Hi @enumag, what do you exactly mean by 'SQl complexity'? The length in chars? Execution time? Other metrics?

Primarily execution time and efficient usage of indexes on that table.

Secondary is the SQL query length and number of conditions in WHERE clause but I'm already using an SQL builder so I can deal with that myself.

**Comment by bedecost** [comment] 2020-04-13 22:57
Thank you @mattecapu. I had the same "algorithm" in my head, but I forgot to reverse the result when using last / before.. which makes senses from the UI point of view.

If someone is interested, here is my current implementation with Node, Apollo, and Knex on top of MySQL. Constructive feedbacks are more than welcome!

I took some shortcuts that I could improve in the future:
- Currently the cursor is an ID --> I should use Base64 to apply the opaque principle
- In my case, selection based on ID (greater/smaller, order by asc/desc) is sufficient in my current project, but it could be improved to be "generic". Although, it has been mentioned above: having a full bulletproof solution might not be that easy to achieve.

```js
const userSchema = gql`

    type User implements Node {
        id: ID!
        email: String!
        ...
    }

    extend type Query {
        ...
        usersPaginated(input: UserPaginatedInput!): UserPaginatedConnection
    }

    input UserPaginatedInput {
        first: Int
        after: ID
        last: Int
        before: ID
    }

    type UserPaginatedConnection {
        pageInfo: PageInfo
        edges: [UserPaginatedEdge]
    }

    type PageInfo {
        hasNextPage: Boolean
        endCursor: ID
        hasPreviousPage: Boolean
        startCursor: ID
    }

    type UserPaginatedEdge {
        cursor: ID
        node: User
    }
    ...
`

const userResolvers = {
    ...
    usersPaginated: async (parent, args, { db }, info) => {
        try {
            const { first, after, last, before } = args.input
            let [hasNextPage, endCursor, hasPreviousPage, startCursor] = [false, null, false, null]
            let res = []

            if (!!first && !!last)
                throw new ApolloError('Ambiguous query: first and last should not be used together')
            if (!first && !last)
                throw new ApolloError('Missing first or last argument')

            const query = db.from('gql_user')

            if (!!first) {
                if (!!after)
                    query.where('id', '>', after)

                query.limit(first + 1)
                    .orderBy('id', 'asc')

                res = await query

                if (res.length > first) {
                    hasNextPage = true
                    res = res.slice(0, first)
                }
            }

            else if (!!last) {
                if (!!before)
                    query.where('id', '<', before)

                query.limit(last + 1)
                    .orderBy('id', 'desc')

                res = await query

                if (res.length > last) {
                    hasPreviousPage = true
                    res = res.slice(0, last)
                }

                res.reverse()
            }

            startCursor = res[0].id
            endCursor = res[res.length - 1].id

            const pageInfo = {
                hasNextPage,
                endCursor,
                hasPreviousPage,
                startCursor
            }

            let edges = []
            res.map(row => {
                edges.push({
                    cursor: row.id,
                    node: row
                })
            })

            return {
                pageInfo,
                edges
            }
        } catch (err) {
            throw new ApolloError(err.sqlMessage, err.code, err)
        }
    }
    ...
}
```

**Comment by ChristianIvicevic** [comment] 2020-05-14 00:43
Sorry for spamming, but I'd like to thanks @mattecapu for his explanation of the algorithm in one of his prior posts. I was mislead by these cursors based on static arrays and noticed that there must be a different way for pagination of dynamic data such as data from a database where data gets deleted in between pages / accessing different pages during pagination causing anomalies. The detailed description really helped to come up with a correct solution in my project.

**Comment by Sytten** [comment] 2021-06-18 22:57
@mattecapu unless I am mistaken steps 4 and 5 are using the wrong ORDER BY (when using first, it should be ASC and vice-versa). Can you fix so people that find this thread are not more confused than necessary 😅

**Comment by mattecapu** [comment] 2021-06-24 12:00
Hi @Sytten, re-reading [the specification](https://relay.dev/graphql/connections.htm#sec-Edge-order) now it seems that ordering is not dependent on the field, but should be decided by the endpoint.
The `ORDER BY` clause in my algorithm is there to select the right chunk of results, but a side-effect is that the order gets reversed when using `last` as opposed to `first`! So I'll add a mention to this in the original comment.
Thanks!

**Comment by Sytten** [comment] 2021-06-24 13:26
@mattecapu Good that you found that too, but that is not really my point :)
Check the coded algo from https://github.com/graphql/graphql-relay-js/issues/94#issuecomment-613137054, you will see that the ORDER BY is the inverse of your algo (first -> ASC, last -> DESC) and for a good reason. If you take N+1 DESC it wont give you the right dataset assuming an autoincrement Int for first and vice versa. Unless you consider first being the highest IDs then it would make sense but I would specify it.

**Comment by mattecapu** [comment] 2021-06-28 08:52
@Sytten I see. It's quite misleading, indeed. I was paginating in reverse chronological order (as most feeds do nowadays) so 'first' to me meant 'first to be displayed'. This explains my choice of ordering, I will edit to clarify.

**Comment by vamshiaruru-virgodesigns** [comment] 2022-04-26 09:15
Hi @mattecapu sorry for bringing up an old thread, but I need some help.

 I am trying to implement relay pagination with postgres and I am facing the issue where I want to sort on multiple columns. Let us say I have products table. I have an ID column, which is globally unique and auto increments every time something is added. Sorting based on this ID is very easy using the algorithm mentioned above. But what if I want to sort on multiple columns? For example, I want to sort on the Name column (to get products in alphabetical order), and then start executing pagination queries. The ID cursor no longer makes sense, because we are sorting on a different field now. So do I make a name cursor and use that? What if I want to sort based on three or more columns? How would I create a cursor then?
 
  I have created a stock overflow question as well: https://stackoverflow.com/questions/72011183/how-to-implement-graphql-relay-style-cursor-based-pagination-in-postgres-with-s , I don't need answers specific to python, but a recommended general approach is appreciated.

**Comment by irvanherz** [comment] 2024-08-12 02:12
> Well the point is, if you implement a ConnectionType for an endpoint you just need to
> 
> * accept `connectionArgs` parameters
> * return a suitable response in the shape `{ edges: [{ cursor, node }], pageInfo: { hasNextPage, hasPreviousPage, startCursor, endCursor }`
> 
> Cursors can be any string you want. Normally Relay defaults to `arrayconnection:<id>` converted to base64 to make it opaque (you shouldn't actually relay on the implementation details of the cursors).
> 
> I used `<type_name>:<id>` converted to base64 as cursors.
> 
> Then a request to my endpoint look like this
> 
> ```graphql
> endpoint(after: "sdflkjsdlfkjslkdf", first: 10) {
>    # stuff
> }
> ```
> 
> Basically, any request described by [the specification](https://facebook.github.io/relay/graphql/connections.htm) is supported.
> 
> Thus when I get the request I process it in the following way:
> 
> 1. Start from the greedy query: `SELECT * FROM table`
> 2. If the `after` argument is provided, add `id > parsed_cursor` to the `WHERE` clause
> 3. If the `before` argument is provided, add `id < parsed_cursor` to the `WHERE` clause
> 4. If the `first` argument is provided, add `ORDER BY id DESC LIMIT first+1` to the query
> 5. If the `last` argument is provided, add `ORDER BY id ASC LIMIT last+1` to the query
> 6. If the `last` argument is provided, I reverse the order of the results
> 7. If the `first` argument is provided then I set `hasPreviousPage: false` (see spec for a description of this behavior).
> 8. If no less than `first+1` results are returned, I set `hasNextPage: true`, otherwise I set it to `false`.
> 9. If the `last` argument is provided then I set `hasNextPage: false` (see spec for a description of this behavior).
> 10. If no less `last+1` results are returned, I set `hasPreviousPage: true`, otherwise I set it to `false`.
> 
> Using this "algorithm", only the needed data is fetched. While `after` and `before` can be both set, I make sure `first` and `last` args are treated as mutually exclusive to avoid making a mess. The spec itself discourage making requests with both the arguments set.
> 
> Notably, I return an object with the shape described above (and in the linked spec) and I don't use the `connectionFromArray` helper, which expects a _raw_ collection to slice accordingly to the args.
> 
> EDIT: The above algorithm produces array with different orders depending on which of `first` or `last` is used to paginate. This is against [the specification](https://relay.dev/graphql/connections.htm#sec-Edge-order), so there should be one more step:
> 
> > 11. Re-order results in a consistent manner (e.g. by creation date)
> 
> Thanks to @Sytten for bringing this problem to my attention.
> 
> EDIT2: The above ordering reflects pagination, not chronological order. Hence `first` is interpreted as 'first to be displayed', not 'first chronologically'. Therefore, you might want to swap `ASC` and `DESC` in step (4) and (5). Thanks to @Sytten for bringing this problem to my attention.

This is what I do, using TypeORM and type-graphql.
```ts
@Query(returns => UserConnection)
  async getUsers(@Args() conn: UserConnectionArgs): Promise<UserConnection> {
    const result = new UserConnection()
    let userQuery = this.userRepository.createQueryBuilder()
    if (conn.search) {
      userQuery = userQuery.where('username LIKE :search', { search: `%${conn.search}%` })
    }
    if (conn.after) {
      userQuery = userQuery.where('id > :id', { id: conn.decodedAfter })
    }
    if (conn.before) {
      userQuery = userQuery.where('id < :id', { id: conn.decodedBefore })
    }
    if (!conn.first && !conn.last) conn.first = 10

    if (conn.first || !conn.last) {
      userQuery = userQuery.orderBy('id', 'ASC')
      conn.first ||= 10
      const users = await userQuery.take(conn.first + 1).getMany()
      result.edges = users.slice(0, conn.first).map(u => ({ node: u, cursor: btoa(u.id.toString()) }))
      result.pageInfo.hasNextPage = users.length > conn.first
      result.pageInfo.hasPreviousPage = false
      result.pageInfo.startCursor = result.edges[0]?.cursor || null
      result.pageInfo.endCursor = result.edges[result.edges.length - 1]?.cursor || null
    }
    if (conn.last) {
      userQuery = userQuery.orderBy('id', 'DESC')
      let users = await userQuery.take(conn.last + 1).getMany()
      users = users.reverse()
      result.edges = users.slice(0, conn.last).map(u => ({ node: u, cursor: btoa(u.id.toString()) }))
      result.pageInfo.hasNextPage = false
      result.pageInfo.hasPreviousPage = users.length > conn.last
      result.pageInfo.startCursor = result.edges[0]?.cursor || null
      result.pageInfo.endCursor = result.edges[result.edges.length - 1]?.cursor || null
    }

    return result
  }
```
